defmodule Cgc2046Web.AuthPlug do
  @moduledoc """
  Auth plug for resolving the actor from an `Authorization: Bearer <JWT>` header.

  - `load_from_bearer/2` (generated by `AshAuthentication.Plug`) verifies the JWT
    issued by `Cgc2046.Accounts.Token` and loads the user into `conn.assigns[:current_user]`.
  - `load_actor/2` promotes that user into the Ash actor (via `Ash.PlugHelpers`),
    which `AshGraphql.Plug` then places into the Absinthe context so Ash policies
    can enforce actor-based rules (e.g. only platform admins may create workspaces).
  """
  use AshAuthentication.Plug, otp_app: :cgc_2046

  @doc """
  Sets the authenticated user (loaded from bearer token) as the Ash actor.

  Place this plug after `load_from_bearer/2` and before `AshGraphql.Plug`.
  """
  def load_actor(conn, _opts) do
    case conn.assigns[:current_user] do
      nil -> conn
      user -> Ash.PlugHelpers.set_actor(conn, user)
    end
  end
end
