defmodule Cgc2046Web.Endpoint do
  use Phoenix.Endpoint, otp_app: :cgc_2046

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_cgc_2046_key",
    signing_salt: "syKPbp2a",
    same_site: "Lax"
  ]

  socket("/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]
  )

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug(Plug.Static,
    at: "/",
    from: :cgc_2046,
    gzip: not code_reloading?,
    only: Cgc2046Web.static_paths(),
    raise_on_missing_only: code_reloading?
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug(Phoenix.CodeReloader)
    plug(Phoenix.Ecto.CheckRepoStatus, otp_app: :cgc_2046)
  end

  plug(Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"
  )

  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  plug(CORSPlug, origin: &__MODULE__.cors_origin/0)

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # 缴费闭环 U6（KTD4）：渠道回调验签需要 raw body 原文（缓存到
    # conn.private[:raw_body]，解析行为零变化）
    body_reader: {Cgc2046Web.Plugs.CachingBodyReader, :read_body, []}
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(Plug.Session, @session_options)
  plug(Cgc2046Web.Router)

  @doc """
  Reads allowed CORS origins from application config.
  Set via `CORS_ORIGIN` env var (comma-separated); defaults to `["http://localhost:3000"]`.
  """
  def cors_origin, do: Application.get_env(:cgc_2046, :cors_origin)
end
