defmodule Cgc2046Web.Endpoint do
  use Phoenix.Endpoint, otp_app: :cgc_2046

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_cgc_2046_key",
    signing_salt: "syKPbp2a",
    same_site: "Lax"
  ]

  # #278 代理信任集（编译期常量——plug 宏编译期求值，运行时函数不可见）：
  # - PROD：kamal docker 网络 172.16.0.0/12（hairpin 实测对端=proxy 容器
  #   172.18.0.3 / Next 容器 172.18.0.7）+ loopback（本机健康探针）
  # - dev/test：proxies 空 + headers 空——peer 即真实 IP，XFF 完全不解析
  if Mix.env() == :prod do
    @trusted_proxies ["172.16.0.0/12", "127.0.0.1", "::1"]
    @proxy_forward_headers ["x-forwarded-for"]
  else
    @trusted_proxies []
    @proxy_forward_headers []
  end

  socket("/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]
  )

  # /ops/* 经 kamal-proxy path 路由直达本容器（主域浏览器会话，方案 #A1）。
  # LiveView WebSocket 必须落在同前缀下才能被同一条 path 规则覆盖；
  # check_origin 显式含主域（默认从 endpoint url 推导出的是 api 子域）。
  socket("/ops/live", Phoenix.LiveView.Socket,
    websocket: [
      check_origin: ["https://codingirlsclub.com"],
      connect_info: [session: @session_options]
    ],
    longpoll: [
      check_origin: ["https://codingirlsclub.com"],
      connect_info: [session: @session_options]
    ]
  )

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug(Plug.Static,
    at: "/",
    from: :cgc_2046,
    gzip: not code_reloading?,
    only: Cgc2046Web.static_paths(),
    raise_on_missing_only: code_reloading?
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug(Phoenix.CodeReloader)
    plug(Phoenix.Ecto.CheckRepoStatus, otp_app: :cgc_2046)
  end

  plug(Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"
  )

  # #278：代理链真实 client IP。生产链路 kamal-proxy（→Next rewrite→）→
  # Phoenix，socket peer 恒为 172.18 网段代理（实测 2026-08-21）——不解析
  # XFF 则 per-IP 限流全站共享一个桶。信任集见 trusted_proxies/0。
  # dev/test 无代理（peer 即真实 IP），headers 为空 = no-op。
  plug(RemoteIp,
    headers: @proxy_forward_headers,
    proxies: @trusted_proxies
  )

  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  plug(CORSPlug, origin: &__MODULE__.cors_origin/0)

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # 缴费闭环 U6（KTD4）：渠道回调验签需要 raw body 原文（缓存到
    # conn.private[:raw_body]，解析行为零变化）
    body_reader: {Cgc2046Web.Plugs.CachingBodyReader, :read_body, []}
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(Plug.Session, @session_options)
  plug(Cgc2046Web.Router)

  @doc """
  Reads allowed CORS origins from application config.
  Set via `CORS_ORIGIN` env var (comma-separated); defaults to `["http://localhost:3000"]`.
  """
  def cors_origin, do: Application.get_env(:cgc_2046, :cors_origin)
end
