import Config

# worktree 并行隔离：附属 git worktree 各用各的库（规则见 worktree_suffix.exs）；
# 主 checkout 库名 cgc_2046_dev。端口取 PORT（见 runtime.exs）。
{branch_suffix, _} = Code.eval_file("worktree_suffix.exs", __DIR__)

# Configure your database
config :cgc_2046, Cgc2046.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "cgc_2046_dev" <> branch_suffix,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :cgc_2046, Cgc2046Web.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :cgc_2046, dev_routes: true

# httpOnly auth cookie: allow non-Secure in dev (localhost HTTP)
config :cgc_2046, :auth_cookie_secure, false

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# 缴费闭环 U4（KTD7）：dev 占位密钥——真实密钥经环境变量注入（可本地联调，
# 不进 git）。渠道调用只在密钥就位时发生，缺席时 adapter 明确拒绝。
config :cgc_2046,
  wechat_pay: [
    mch_id: System.get_env("WECHAT_PAY_MCH_ID"),
    appid: System.get_env("WECHAT_PAY_APPID"),
    api_v3_key: System.get_env("WECHAT_PAY_API_V3_KEY"),
    api_secret_v2_key: System.get_env("WECHAT_PAY_API_V2_KEY"),
    client_serial_no: System.get_env("WECHAT_PAY_CLIENT_SERIAL_NO"),
    client_private_key: System.get_env("WECHAT_PAY_CLIENT_PRIVATE_KEY"),
    webhook_base_url: System.get_env("PAYMENTS_WEBHOOK_BASE_URL") || "http://localhost:4000"
  ],
  alipay_pay: [
    app_id: System.get_env("ALIPAY_APP_ID"),
    private_key: System.get_env("ALIPAY_PRIVATE_KEY"),
    public_key: System.get_env("ALIPAY_PUBLIC_KEY"),
    webhook_base_url: System.get_env("PAYMENTS_WEBHOOK_BASE_URL") || "http://localhost:4000",
    return_url: System.get_env("ALIPAY_RETURN_URL"),
    # 沙箱联调开关（host 切 openapi-sandbox.dl.alipaydev.com；生产保持缺省 false）
    sandbox: System.get_env("ALIPAY_SANDBOX") == "true"
  ]

# dev 环境补 endpoint secret：/dev 作用域（mailbox 预览等）走 cookie session，
# 缺 secret_key_base 会在详情页 500（生产从 runtime.exs 的 SECRET_KEY_BASE 注入）。
config :cgc_2046, Cgc2046Web.Endpoint,
  secret_key_base: "dv1ZLRPVvn2Yr4WmGRNSLzFB4qbtDhyaQPJXBUDDdtUcJ5dCcAGKfh4ACqmPhLXK"
