defmodule Cgc2046.Repo.Migrations.SliceCEventsCourses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "events_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :title, :text, null: false
      add :research_enabled, :boolean, null: false, default: true
      add :research_requirements, :map, default: %{}
      add :status, :text, null: false, default: "draft"

      add :workflow_run_id,
          references(:workflow_runs,
            column: :id,
            name: "events_workflow_run_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:courses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "courses_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :title, :text, null: false
      add :research_enabled, :boolean, null: false, default: true
      add :research_requirements, :map, default: %{}
      add :status, :text, null: false, default: "draft"

      add :workflow_run_id,
          references(:workflow_runs,
            column: :id,
            name: "courses_workflow_run_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:courses, "courses_workspace_id_fkey")

    drop constraint(:courses, "courses_workflow_run_id_fkey")

    drop table(:courses)

    drop constraint(:events, "events_workspace_id_fkey")

    drop constraint(:events, "events_workflow_run_id_fkey")

    drop table(:events)
  end
end
