defmodule Cgc2046.Repo.Migrations.AddOauthUsersFk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:oauth_consents) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "oauth_consents_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:oauth_refresh_tokens) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "oauth_refresh_tokens_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:oauth_authorization_codes) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "oauth_authorization_codes_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:oauth_authorization_codes, "oauth_authorization_codes_user_id_fkey")

    alter table(:oauth_authorization_codes) do
      modify :user_id, :uuid
    end

    drop constraint(:oauth_refresh_tokens, "oauth_refresh_tokens_user_id_fkey")

    alter table(:oauth_refresh_tokens) do
      modify :user_id, :uuid
    end

    drop constraint(:oauth_consents, "oauth_consents_user_id_fkey")

    alter table(:oauth_consents) do
      modify :user_id, :uuid
    end
  end
end
