defmodule Cgc2046.Repo.Migrations.CreateWorkspaces do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workspaces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :name, :text, null: false
      add :join_policy, :text, null: false, default: "request"
      add :sponsorship_enabled, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:workspaces, [:slug], name: "workspaces_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:workspaces, [:slug], name: "workspaces_unique_slug_index")

    drop table(:workspaces)
  end
end
