defmodule Cgc2046.Repo.Migrations.T06JoinFlow do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "profiles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :avatar_url, :text
      add :bio, :text
      add :tags, {:array, :text}, default: []
      add :portfolio, {:array, :text}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "profiles_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:profiles, [:workspace_id, :user_id],
             name: "profiles_unique_user_per_workspace_index"
           )

    create table(:join_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "join_requests_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :status, :text, null: false, default: "pending"
      add :requested_role_ids, {:array, :uuid}, default: []
      add :decided_by, :uuid
      add :decided_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "join_requests_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:join_requests, "join_requests_user_id_fkey")

    drop constraint(:join_requests, "join_requests_workspace_id_fkey")

    drop table(:join_requests)

    drop constraint(:profiles, "profiles_user_id_fkey")

    drop constraint(:profiles, "profiles_workspace_id_fkey")

    drop_if_exists unique_index(:profiles, [:workspace_id, :user_id],
                     name: "profiles_unique_user_per_workspace_index"
                   )

    drop table(:profiles)
  end
end
