defmodule Cgc2046.Repo.Migrations.AddWorkspaceMembershipUniqueUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspace_memberships) do
      modify :workspace_id, :uuid, null: false
    end

    create unique_index(:workspace_memberships, [:workspace_id, :user_id],
             name: "workspace_memberships_unique_user_per_workspace_index"
           )
  end

  def down do
    drop_if_exists unique_index(:workspace_memberships, [:workspace_id, :user_id],
                     name: "workspace_memberships_unique_user_per_workspace_index"
                   )

    alter table(:workspace_memberships) do
      modify :workspace_id, :uuid, null: true
    end
  end
end
