defmodule Cgc2046.Repo.Migrations.SliceCSignalLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:signal_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false

      # run_id 不加 FK 约束（signal 日志在 run 删除后仍保留审计，计划 §步骤 3）
      add :run_id, :uuid, null: false

      add :signal_type, :text, null: false
      add :payload, :map, default: %{}
      add :actor_id, :uuid
      add :received_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:signal_logs, [:workspace_id, :run_id])
  end

  def down do
    drop_if_exists index(:signal_logs, [:workspace_id, :run_id])

    drop table(:signal_logs)
  end
end
