defmodule Cgc2046.Repo.Migrations.CreateFlashbackWishes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:flashback_wish_endorsements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :wish_id, :uuid, null: false
      add :person_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:flashback_wish_endorsements, [:wish_id, :person_id],
             name: "flashback_wish_endorsements_unique_wish_person_index"
           )

    create table(:flashback_wishes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :person_id,
          references(:flashback_people,
            column: :id,
            name: "flashback_wishes_person_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing
          ),
          null: false

      add :content, :text, null: false
      add :visibility, :text, null: false
      add :city, :text
      add :deleted_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:flashback_wish_comments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :wish_id, :uuid, null: false
      add :person_id, :uuid, null: false
      add :content, :text, null: false
      add :deleted_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:flashback_wish_comments)

    drop constraint(:flashback_wishes, "flashback_wishes_person_id_fkey")

    drop table(:flashback_wishes)

    drop_if_exists unique_index(:flashback_wish_endorsements, [:wish_id, :person_id],
                     name: "flashback_wish_endorsements_unique_wish_person_index"
                   )

    drop table(:flashback_wish_endorsements)
  end
end
