defmodule Cgc2046.Repo.Migrations.SliceCWorkflowRun do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workflow_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false

      add :definition_id,
          references(:workflow_definitions,
            column: :id,
            name: "workflow_runs_definition_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :definition_version, :bigint, null: false
      add :status, :text, null: false, default: "pending"
      add :input_snapshot, :map
      add :facts, :map, default: %{}
      add :partition_id, :uuid
      add :version, :bigint, null: false, default: 1
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:workflow_definitions) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "workflow_definitions_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:workflow_definitions, [:workspace_id])
  end

  def down do
    drop_if_exists index(:workflow_definitions, [:workspace_id])

    drop constraint(:workflow_definitions, "workflow_definitions_workspace_id_fkey")

    alter table(:workflow_definitions) do
      modify :workspace_id, :uuid
    end

    drop constraint(:workflow_runs, "workflow_runs_definition_id_fkey")

    drop table(:workflow_runs)
  end
end
