defmodule Cgc2046.Repo.Migrations.T05PermissionMatrix do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workflows, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :dsl_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "workflows_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:steps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :position, :bigint, null: false
      add :type, :text
      add :agent_hint, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "steps_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :workflow_id,
          references(:workflows,
            column: :id,
            name: "steps_workflow_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:step_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "step_roles_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :step_id,
          references(:steps,
            column: :id,
            name: "step_roles_step_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :role_id,
          references(:roles,
            column: :id,
            name: "step_roles_role_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:step_roles, [:workspace_id, :step_id, :role_id],
             name: "step_roles_unique_step_role_index"
           )

    alter table(:roles) do
      modify :workspace_id, :uuid, null: false
    end

    alter table(:membership_roles) do
      modify :role_id, :uuid, null: false
      modify :membership_id, :uuid, null: false
      modify :workspace_id, :uuid, null: false
    end

    create table(:invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token_hash, :text, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :target_email, :text
      add :preauthorized_role_ids, {:array, :uuid}, null: false, default: []
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "invitations_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :inviter_id,
          references(:users,
            column: :id,
            name: "invitations_inviter_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:audit_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :actor_id, :uuid
      add :client, :text
      add :action, :text, null: false
      add :resource, :text
      add :workspace_id, :uuid
      add :ip, :text
      add :result, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:agents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :type, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "agents_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :owner_id,
          references(:workspace_memberships,
            column: :id,
            name: "agents_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:agent_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "agent_roles_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :agent_id,
          references(:agents,
            column: :id,
            name: "agent_roles_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :role_id,
          references(:roles,
            column: :id,
            name: "agent_roles_role_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:agent_roles, [:workspace_id, :agent_id, :role_id],
             name: "agent_roles_unique_agent_role_index"
           )
  end

  def down do
    drop constraint(:agent_roles, "agent_roles_workspace_id_fkey")

    drop constraint(:agent_roles, "agent_roles_agent_id_fkey")

    drop constraint(:agent_roles, "agent_roles_role_id_fkey")

    drop_if_exists unique_index(:agent_roles, [:workspace_id, :agent_id, :role_id],
                     name: "agent_roles_unique_agent_role_index"
                   )

    drop table(:agent_roles)

    drop constraint(:agents, "agents_workspace_id_fkey")

    drop constraint(:agents, "agents_owner_id_fkey")

    drop table(:agents)

    drop table(:audit_logs)

    drop constraint(:invitations, "invitations_workspace_id_fkey")

    drop constraint(:invitations, "invitations_inviter_id_fkey")

    drop table(:invitations)

    alter table(:membership_roles) do
      modify :workspace_id, :uuid, null: true
      modify :membership_id, :uuid, null: true
      modify :role_id, :uuid, null: true
    end

    alter table(:roles) do
      modify :workspace_id, :uuid, null: true
    end

    drop constraint(:step_roles, "step_roles_workspace_id_fkey")

    drop constraint(:step_roles, "step_roles_step_id_fkey")

    drop constraint(:step_roles, "step_roles_role_id_fkey")

    drop_if_exists unique_index(:step_roles, [:workspace_id, :step_id, :role_id],
                     name: "step_roles_unique_step_role_index"
                   )

    drop table(:step_roles)

    drop constraint(:steps, "steps_workspace_id_fkey")

    drop constraint(:steps, "steps_workflow_id_fkey")

    drop table(:steps)

    drop constraint(:workflows, "workflows_workspace_id_fkey")

    drop table(:workflows)
  end
end
