defmodule Cgc2046.Repo.Migrations.AddToolCallLogIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:mcp_tool_call_logs, ["((params->>'workspace_id'))"],
             name: "mcp_tool_call_logs_params_workspace_id_index",
             concurrently: true
           )

    create index(:mcp_tool_call_logs, [:inserted_at], concurrently: true)
  end

  def down do
    drop_if_exists index(:mcp_tool_call_logs, [:inserted_at])

    drop_if_exists index(:mcp_tool_call_logs, ["((params->>'workspace_id'))"],
                     name: "mcp_tool_call_logs_params_workspace_id_index"
                   )
  end
end
