defmodule Cgc2046.Repo.Migrations.AddOauthRefreshTokensIdentityIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:oauth_refresh_tokens, [:user_id, :client_id])
  end

  def down do
    drop_if_exists index(:oauth_refresh_tokens, [:user_id, :client_id])
  end
end
