defmodule Cgc2046.Repo.Migrations.AddRolesMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`，
  并手工改写为幂等版本：dev 库存在旧 schema 遗留的同名空表（#62 遗留），
  不能 drop 重建（step_roles/agents/agent_roles 等有外键依赖），因此对已存在
  的表只做 ALTER（补列/清多余列/对齐索引），对不存在的表正常 CREATE。
  """

  use Ecto.Migration

  defp table_exists?(table) do
    repo()
    |> Ecto.Adapters.SQL.query!("SELECT to_regclass('public.#{table}') IS NOT NULL", [])
    |> then(fn result -> result.rows |> hd |> hd end)
  end

  defp index_exists?(table, name) do
    repo()
    |> Ecto.Adapters.SQL.query!(
      "SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = $1 AND indexname = $2",
      [to_string(table), to_string(name)]
    )
    |> then(fn result -> result.num_rows > 0 end)
  end

  defp column_exists?(table, column) do
    repo()
    |> Ecto.Adapters.SQL.query!(
      "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = $1 AND column_name = $2",
      [to_string(table), to_string(column)]
    )
    |> then(fn result -> result.num_rows > 0 end)
  end

  def up do
    # ---------- workspace_memberships ----------
    if table_exists?(:workspace_memberships) do
      drop_if_exists unique_index(:workspace_memberships, [:workspace_id, :user_id],
                       name: "workspace_memberships_unique_user_per_workspace_index"
                     )

      # 新索引名（短，避免超长）
      unless index_exists?(:workspace_memberships, "wm_unique_ws_user_idx") do
        create unique_index(:workspace_memberships, [:workspace_id, :user_id],
                 name: "wm_unique_ws_user_idx"
               )
      end
    else
      create table(:workspace_memberships, primary_key: false) do
        add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

        add :workspace_id,
            references(:workspaces,
              column: :id,
              name: "workspace_memberships_workspace_id_fkey",
              type: :uuid,
              prefix: "public"
            ),
            null: false

        add :user_id,
            references(:users,
              column: :id,
              name: "workspace_memberships_user_id_fkey",
              type: :uuid,
              prefix: "public"
            ),
            null: false

        add :inserted_at, :utc_datetime_usec,
          null: false,
          default: fragment("(now() AT TIME ZONE 'utc')")

        add :updated_at, :utc_datetime_usec,
          null: false,
          default: fragment("(now() AT TIME ZONE 'utc')")
      end

      create unique_index(:workspace_memberships, [:workspace_id, :user_id],
               name: "wm_unique_ws_user_idx"
             )
    end

    # ---------- roles ----------
    if table_exists?(:roles) do
      # 旧 schema 多余的 permissions 列（0 行数据，可直接删）
      if column_exists?(:roles, :permissions) do
        alter table(:roles) do
          remove :permissions
        end
      end

      drop_if_exists unique_index(:roles, [:workspace_id, :name],
                       name: "roles_unique_name_per_workspace_index"
                     )

      unless index_exists?(:roles, "roles_unique_role_per_workspace_index") do
        create unique_index(:roles, [:workspace_id, :name],
                 name: "roles_unique_role_per_workspace_index"
               )
      end
    else
      create table(:roles, primary_key: false) do
        add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
        add :workspace_id, :uuid, null: false
        add :name, :text, null: false
        add :description, :text

        add :inserted_at, :utc_datetime_usec,
          null: false,
          default: fragment("(now() AT TIME ZONE 'utc')")

        add :updated_at, :utc_datetime_usec,
          null: false,
          default: fragment("(now() AT TIME ZONE 'utc')")
      end

      create unique_index(:roles, [:workspace_id, :name],
               name: "roles_unique_role_per_workspace_index"
             )
    end

    # ---------- membership_roles ----------
    if table_exists?(:membership_roles) do
      unless index_exists?(:membership_roles, "membership_roles_unique_membership_role_index") do
        create unique_index(:membership_roles, [:workspace_id, :membership_id, :role_id],
                 name: "membership_roles_unique_membership_role_index"
               )
      end
    else
      create table(:membership_roles, primary_key: false) do
        add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
        add :workspace_id, :uuid, null: false

        add :inserted_at, :utc_datetime_usec,
          null: false,
          default: fragment("(now() AT TIME ZONE 'utc')")

        add :updated_at, :utc_datetime_usec,
          null: false,
          default: fragment("(now() AT TIME ZONE 'utc')")

        add :membership_id,
            references(:workspace_memberships,
              column: :id,
              name: "membership_roles_membership_id_fkey",
              type: :uuid,
              prefix: "public"
            ),
            null: false

        add :role_id,
            references(:roles,
              column: :id,
              name: "membership_roles_role_id_fkey",
              type: :uuid,
              prefix: "public"
            ),
            null: false
      end

      create unique_index(:membership_roles, [:workspace_id, :membership_id, :role_id],
               name: "membership_roles_unique_membership_role_index"
             )
    end
  end

  def down do
    # 幂等 down：仅删除本次创建的索引与多余列；不 drop 表（dev 库有外键依赖）
    drop_if_exists unique_index(:membership_roles, [:workspace_id, :membership_id, :role_id],
                     name: "membership_roles_unique_membership_role_index"
                   )

    drop_if_exists unique_index(:roles, [:workspace_id, :name],
                     name: "roles_unique_role_per_workspace_index"
                   )

    drop_if_exists unique_index(:workspace_memberships, [:workspace_id, :user_id],
                     name: "wm_unique_ws_user_idx"
                   )

    if column_exists?(:roles, :permissions) do
      alter table(:roles) do
        remove :permissions
      end
    end
  end
end
