defmodule Cgc2046.Repo.Migrations.AddWorkspacesAndIsPlatformAdmin do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workspaces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :name, :text, null: false
      add :join_policy, :text, null: false, default: "request"

      add :owner_id,
          references(:users,
            column: :id,
            name: "workspaces_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:workspaces, [:slug], name: "workspaces_unique_slug_index")

    create table(:workspace_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "workspace_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "workspace_memberships_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:users) do
      add :is_platform_admin, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:users) do
      remove :is_platform_admin
    end

    drop constraint(:workspace_memberships, "workspace_memberships_user_id_fkey")

    drop constraint(:workspace_memberships, "workspace_memberships_workspace_id_fkey")

    drop table(:workspace_memberships)

    drop constraint(:workspaces, "workspaces_owner_id_fkey")

    drop_if_exists unique_index(:workspaces, [:slug], name: "workspaces_unique_slug_index")

    drop table(:workspaces)
  end
end
