defmodule Cgc2046.Repo.Migrations.WorkflowSliceC do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workflow_steps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false
      add :definition_id, :uuid, null: false
      add :step_key, :text, null: false
      add :title, :text, null: false
      add :type, :text, null: false
      add :action, :text
      add :agent_id, :uuid
      add :sub_definition_id, :uuid
      add :input_schema, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:workflow_steps, [:workspace_id, :definition_id, :step_key],
             name: "workflow_steps_unique_step_key_per_definition_index"
           )

    create table(:workflow_step_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :workspace_id, :uuid, null: false

      add :step_id,
          references(:workflow_steps,
            column: :id,
            name: "workflow_step_roles_step_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :role_id,
          references(:roles,
            column: :id,
            name: "workflow_step_roles_role_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:workflow_step_roles, [:workspace_id, :step_id, :role_id],
             name: "workflow_step_roles_unique_step_role_index"
           )

    create table(:workflow_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:workflow_steps) do
      modify :definition_id,
             references(:workflow_definitions,
               column: :id,
               name: "workflow_steps_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:workflow_definitions) do
      add :workspace_id, :uuid, null: false
      add :name, :text, null: false
      add :type, :text, null: false
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "draft"
      add :input_schema, :map
      add :node_def, :map
      add :approval_timeout, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:workflow_definitions, [:workspace_id, :name, :version],
             name: "workflow_definitions_unique_name_version_per_workspace_index"
           )
  end

  def down do
    drop_if_exists unique_index(:workflow_definitions, [:workspace_id, :name, :version],
                     name: "workflow_definitions_unique_name_version_per_workspace_index"
                   )

    alter table(:workflow_definitions) do
      remove :updated_at
      remove :inserted_at
      remove :approval_timeout
      remove :node_def
      remove :input_schema
      remove :status
      remove :version
      remove :type
      remove :name
      remove :workspace_id
    end

    drop constraint(:workflow_steps, "workflow_steps_definition_id_fkey")

    alter table(:workflow_steps) do
      modify :definition_id, :uuid
    end

    drop table(:workflow_definitions)

    drop constraint(:workflow_step_roles, "workflow_step_roles_step_id_fkey")

    drop constraint(:workflow_step_roles, "workflow_step_roles_role_id_fkey")

    drop_if_exists unique_index(:workflow_step_roles, [:workspace_id, :step_id, :role_id],
                     name: "workflow_step_roles_unique_step_role_index"
                   )

    drop table(:workflow_step_roles)

    drop_if_exists unique_index(:workflow_steps, [:workspace_id, :definition_id, :step_key],
                     name: "workflow_steps_unique_step_key_per_definition_index"
                   )

    drop table(:workflow_steps)
  end
end
