defmodule Cgc2046.Repo.Migrations.AddRolesAndMembershipRoles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :permissions, {:array, :text}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "roles_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:roles, [:workspace_id, :name],
             name: "roles_unique_name_per_workspace_index"
           )

    create table(:membership_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "membership_roles_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :membership_id,
          references(:workspace_memberships,
            column: :id,
            name: "membership_roles_membership_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :role_id,
          references(:roles,
            column: :id,
            name: "membership_roles_role_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:membership_roles, [:workspace_id, :membership_id, :role_id],
             name: "membership_roles_unique_membership_role_index"
           )
  end

  def down do
    drop constraint(:membership_roles, "membership_roles_workspace_id_fkey")

    drop constraint(:membership_roles, "membership_roles_membership_id_fkey")

    drop constraint(:membership_roles, "membership_roles_role_id_fkey")

    drop_if_exists unique_index(:membership_roles, [:workspace_id, :membership_id, :role_id],
                     name: "membership_roles_unique_membership_role_index"
                   )

    drop table(:membership_roles)

    drop constraint(:roles, "roles_workspace_id_fkey")

    drop_if_exists unique_index(:roles, [:workspace_id, :name],
                     name: "roles_unique_name_per_workspace_index"
                   )

    drop table(:roles)
  end
end
