defmodule Cgc2046.Repo.Migrations.AddEventCompanionRevision do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :course_revision_id, :uuid
    end

    # D4 挂载授权反查（「该课程 revision 被哪些 event 锚定」）走此索引
    create_if_not_exists index(:events, [:course_revision_id])
  end

  def down do
    alter table(:events) do
      remove :course_revision_id
    end
  end
end
